version: '3.8'

services:
  comfyui:
    image: nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04
    container_name: comfyui
    restart: unless-stopped
    runtime: nvidia
    ports:
      - "8188:8188"
    volumes:
      - ./app:/ComfyUI
      - ./inputs:/ComfyUI/input
      - ./outputs:/ComfyUI/output
      - ./models:/ComfyUI/models
      - ./custom_nodes:/ComfyUI/custom_nodes
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
    command: >
      bash -c "
        apt-get update && 
        apt-get install -y python3 python3-pip git &&
        if [ ! -d '/ComfyUI/.git' ]; then
          git clone https://github.com/comfyanonymous/ComfyUI.git /ComfyUI_tmp &&
          cp -r /ComfyUI_tmp/. /ComfyUI/ &&
          rm -rf /ComfyUI_tmp
        fi &&
        cd /ComfyUI &&
        pip3 install -r requirements.txt &&
        pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128 &&
        mkdir -p /ComfyUI/custom_nodes &&
        if [ ! -d '/ComfyUI/custom_nodes/ComfyUI-Manager' ]; then
          git clone https://github.com/Comfy-Org/ComfyUI-Manager.git /ComfyUI/custom_nodes/ComfyUI-Manager
        fi &&
        python3 main.py --listen 0.0.0.0 --port 8188 --cuda-device=0
      "
